// Generated by CoffeeScript 1.6.3
(function() {
  var a, b, c, d, pre;

  (function(window, me) {
    "use strict";
    var self, setDiff;
    self = window[me] || (window[me] = {});
    setDiff = function(f, l) {
      var i, result, _i, _len;
      result = '';
      l.contains = function(el) {
        var x, _i, _len;
        for (_i = 0, _len = this.length; _i < _len; _i++) {
          x = this[_i];
          if (x === el) {
            return true;
          }
        }
        return false;
      };
      for (_i = 0, _len = f.length; _i < _len; _i++) {
        i = f[_i];
        if (!l.contains(i)) {
          result += i + " ";
        }
      }
      return result;
    };
    return window[me].setDifference = setDiff;
  })(this, "ilpaijin");

  a = [1, 2, 3, 8, 9];

  b = [2, 5, 9, 10, 12, 14];

  c = ["Boys", "Girls", "Zend", "Barcelona", "Come 'on"];

  d = ["Jurgen", "Berlusconi", "Paté di pato", "Frio", "Boys", "Zend"];

  pre = document.getElementById("coffeeresponse");

  pre.appendChild(document.createTextNode("{A - B} = " + ilpaijin.setDifference(a, b)));

  pre.appendChild(document.createElement("br"));

  pre.appendChild(document.createTextNode("{B - A} = " + ilpaijin.setDifference(b, a)));

  pre.appendChild(document.createElement("br"));

  pre.appendChild(document.createTextNode("{C - D} = " + ilpaijin.setDifference(c, d)));

  pre.appendChild(document.createElement("br"));

  pre.appendChild(document.createTextNode("{D - C} = " + ilpaijin.setDifference(d, c)));

}).call(this);
